Repository naveen701526/My-Projects, pull requests merged in 2022-10, with the labels that each got.

#63 Translator.py
  Python /Translator.py
Labels: hacktoberfest-accepted, hacktoberfest2022

#66 Update README.md
  README.md
Labels: hacktoberfest-accepted, hacktoberfest2022

#65 Create Find_number_game.java
  Java/Exercise Problems/Find_number_game.java
Labels: hacktoberfest-accepted, hacktoberfest2022

#64 Create Stone_Paper_Scissor_Game.py
  Python/Projects/Stone Paper Scissor/Stone_Paper_Scissor_Game.py
Labels: hacktoberfest-accepted, hacktoberfest2022

#67 Create StonePaperScissor.java
  Java/Exercise Problems/StonePaperScissor.java
Labels: hacktoberfest-accepted, hacktoberfest2022

#70 Create Aerial-distance-calculator.py
  Python /Aerial-distance-calculator.py
Labels: hacktoberfest-accepted, hacktoberfest2022

#73 Create PathSumII113.java
  Java/Leetcode/PathSumII113.java
Labels: hacktoberfest-accepted, hacktoberfest2022

#74 MineSweeper Game
  html, css, js/Minesweeper/README.md
  html, css, js/Minesweeper/index.html
  html, css, js/Minesweeper/script.js
  html, css, js/Minesweeper/style.css
Labels: hacktoberfest-accepted, hacktoberfest2022

#76 Added duplicate file remover script
  Python/Remove_duplicate_files/dup1.txt
  Python/Remove_duplicate_files/dup2.txt
  Python/Remove_duplicate_files/main.py
Labels: hacktoberfest-accepted, hacktoberfest2022

#77 Added hover effect
  HTML + CSS + Js/Hover_effect/index.html
  HTML + CSS + Js/Hover_effect/style.css
Labels: hacktoberfest-accepted, hacktoberfest2022

#80 Create TwoSumIVInputIsBST653.java
  Java/Leetcode/TwoSumIVInputIsBST653.java
Labels: hacktoberfest-accepted, hacktoberfest2022

#82 Dynamic NQueens Solver using tkinter
  Python/Projects/Dynamic NQueens Solver/nqueens.py
Labels: hacktoberfest-accepted

#84 148 Sort List
  Python/Leetcode/148_sort_list.py
Labels: hacktoberfest-accepted

#83 added an animated eye moving with cursor
  html, css, js/Animated Eye/index.html
  html, css, js/Animated Eye/script.js
  html, css, js/Animated Eye/styles.css
Labels: hacktoberfest-accepted, hacktoberfest2022

#85 146. LRU Cache
  146_lru_cache.py
Labels: hacktoberfest-accepted

#86 138. Copy List with Random Pointer
  138_copy_list_with_random_pointer.py
Labels: good first issue

#88 Create roadCrossGame.py
  Python/Projects/roadCrossGame.py
Labels: hacktoberfest-accepted, hacktoberfest2022

#92 MaximumProductOfThreeNumbers628
  Java/Leetcode/MaximumProductOfThreeNumbers628.java
Labels: hacktoberfest-accepted, hacktoberfest2022

#93 Create FloodFill733.java
  Java/Leetcode/FloodFill733.java
Labels: hacktoberfest-accepted

#94 Create ValidNumber65.java
  Java/Leetcode/ValidNumber65.java
Labels: hacktoberfest-accepted, hacktoberfest2022

#95 Create PermutationSequence60.java
  Java/Leetcode/PermutationSequence60.java
Labels: hacktoberfest-accepted, hacktoberfest2022

#100 Implementation of queue using array
  C programs/queueUsingArray.c
Labels: hacktoberfest-accepted

#99 added rocket animation and black jack
  html, css, js/Black_Jack/index.html
  html, css, js/Black_Jack/index.js
  html, css, js/Black_Jack/style.css
  html, css, js/Rocket animation/index.html
Labels: hacktoberfest-accepted

#101 Create FractionToRecurringDecimal166.java
  Java/Leetcode/FractionToRecurringDecimal166.java
Labels: hacktoberfest-accepted

#102 Create CompareVersionNumber165.java
  Java/Leetcode/CompareVersionNumber165.java
Labels: hacktoberfest-accepted

#103 Create FactorialTrailingZeroes172.java
  Java/Leetcode/FactorialTrailingZeroes172.java
Labels: hacktoberfest-accepted

#104 Create InsertInterval57.java
  Java/Leetcode/InsertInterval57.java
Labels: hacktoberfest-accepted

#107 Added Rock,Paper & Scissor game in python projects
  C programs/queueUsingArray.c
  Python /Aerial-distance-calculator.py
  Python /Translator.py
  Python/Exercise Problems/diagonalDifference.py
  Python/Projects/Rock_Paper_Scissor/game.py
  html, css, js/Landing Page/dist/js/simple-lightbox.jquery.js
  html, css, js/Landing Page/dist/js/simple-lightbox.jquery.min.js
  html, css, js/Landing Page/dist/js/simple-lightbox.js
Labels: hacktoberfest-accepted

#106 Added auto spamming program
  Python /spammer.py
Labels: hacktoberfest-accepted

#109 Caesar_Cipher.py
  Python/Projects/Caesar_Cipher.py
Labels: hacktoberfest-accepted
